language: python
python:
- "2.6"
- "2.7"
install:
- pip install WebHelpers
- pip install pydiatra pyflakes
script:
- ./chronodistance -g day 2003-04-14 2004-12-01
- py2diatra chronodistance
- pyflakes chronodistance

# vim:ts=2 sts=2 sw=2 et
