language: python
jobs:
  include:
  - python: "2.6"
  - python: "2.7"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_rstlint=:; fi
install:
- pip install WebHelpers
- pip install pydiatra $pyflakes
- $if_rstlint pip install restructuredtext-lint pygments
script:
- ./chronodistance -g day 2003-04-14 2004-12-01
- py2diatra chronodistance
- pyflakes chronodistance
- $if_rstlint restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
