#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2011-2026 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import datetime
import os
import subprocess as ipc

import webhelpers2.date as datehelper

0_0  # Python >= 3.6 is required

granularities = [
    'century',
    'decade',
    'year',
    'month',
    'day',
    'hour',
    'minute',
    'second',
]

def parse_timestamp(ts=None):
    if ts is None:
        # Shortcut:
        return datetime.datetime.utcnow()
    args = ['date', f'--date={ts}', '+%s']
    child = ipc.Popen(args, stdout=ipc.PIPE, stderr=ipc.PIPE)
    stdout, stderr = child.communicate()
    if stderr:
        stderr = stderr.decode('ASCII')
        raise ValueError(f'Cannot parse date: {stderr}')
    stdout = stdout.decode('ASCII')
    return datetime.datetime.utcfromtimestamp(int(stdout))

def main():
    os.environ['LC_ALL'] = 'C'
    ap = argparse.ArgumentParser()
    ap.add_argument('-g', dest='granularity', metavar='GRANULARITY', choices=granularities, default='minute',
        help=('choices: '  + str.join(', ', granularities))
    )
    ap.add_argument('src', metavar='SRC')
    ap.add_argument('dst', metavar='DST', nargs='?')
    options = ap.parse_args()
    src = parse_timestamp(options.src)
    dst = parse_timestamp(options.dst)
    print(datehelper.distance_of_time_in_words(
        from_time=src, to_time=dst,
        granularity=options.granularity
    ))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
